"use client";

import { useEffect } from "react";
import Image from "next/image";
import Link from "next/link";
import App_layout from "@/layout/app_layout";
import { motion } from "framer-motion";

import AOS from "aos";
import "aos/dist/aos.css";
import Downloadcatalog from "../democatalog/downloadcatalog";
import Downloadcatalogeflyer from "./downloadcatalogeflyer";

const products = [
  {
    name: "TMS",
    image: "/home/tmsproduct.jpeg",
    title: "Transcranial Magnetic Stimulation",
    subtitle: "FDA-Cleared TMS Therapy",
    description:
      "TMS therapy is a non-invasive treatment in which a strong electromagnetic field generated by a coil penetrates the skull and stimulates nerve cells.",
    extra:
      "FDA-cleared for major depressive disorder, anxiety, obsessive-compulsive disorder, and smoking addiction.",
    benefits: [
      "Non-invasive treatment solution",
      "Clinically proven effectiveness",
      "Safe and patient-friendly",
      "Enhances neurological outcomes",
    ],
  },

  {
    name: "PMS",
    image: "/home/pmsimage.jpg",
    title: "Pain Management Solution",
    subtitle: "Comprehensive Pain Treatment Solution",
    description:
      "Premium Electromagnetic Stimulator designed for precise pain therapy with advanced whole-body stimulation technology.",
    extra:
      "User-centered manual modes, flexible angles, and cooling system for continuous use.",
    benefits: [
      "User-centered manual modes",
      "Flexible 3D Angle Arm",
      "Cooling system",
      "Whole-body stimulation",
    ],
  },
];

const galleryImages = [
  "/home/tmsproduct.jpeg",
  "/home/tms treatment-1.jpg",
  "/home/tms treatment-3.jpg",
  "/home/brainstim.jpg",
  "/home/brain eyes.png",
  "/home/pmsimage.jpg",
];

export default function ProductsPage() {
  useEffect(() => {
    AOS.init({
      duration: 1000,
      once: true,
    });
  }, []);

  return (
    <App_layout>
      <div className="bg-black text-white overflow-hidden w-full">
        {/* ===================================================== */}
        {/* MOBILE HERO SECTION */}
        {/* ===================================================== */}

        <section className="md:hidden relative w-full bg-black overflow-hidden">
          {/* IMAGE SECTION */}

          <div className="relative w-[350px] h-[340px] overflow-hidden">
            <Image
              src="/tms product/Product Mobile.jpg"
              alt="Products"
              fill
              priority
              className="object-cover object-center max-sm:mt-12 "
            />

            {/* OVERLAY */}

            {/* <div className="absolute inset-0 bg-black/40 z-[1]" /> */}

            {/* BOTTOM FADE */}

            <div className="absolute bottom-0 left-0 w-full h-20 bg-gradient-to-t from-black to-transparent z-[2]" />
          </div>

          {/* CONTENT BELOW IMAGE */}

          <div
            data-aos="fade-up"
            className="
              relative
              z-10
              px-5
              pt-8
              pb-12
              text-center
            "
          >
            {/* TAG */}

            <motion.div
              initial={{ opacity: 0, y: 15 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.8 }}
              className="
                inline-flex
                items-center
                justify-center
                px-4
                py-2
                rounded-full
                border
                border-[#fed42a]/40
                bg-[#111111]
                text-[#fed42a]
                text-[10px]
                uppercase
                tracking-[2px]
                mb-5
              "
            >
              Korean Healthcare Innovation
            </motion.div>

            {/* TITLE */}

            <motion.h1
              initial={{ opacity: 0, y: 40 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 1 }}
              className="
                font-bold
                leading-[1.3]
                text-[32px]
              "
            >
              Our{" "}
              <span className="text-[#fed42a]">
                Product Line
              </span>
            </motion.h1>

            {/* DESCRIPTION */}

            <motion.p
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              transition={{ delay: 0.3 }}
              className="
                mt-4
                text-[14px]
                text-gray-300
                leading-relaxed
              "
            >
              Carefully selected beauty and healthcare technologies
              from Korea designed for modern wellness experiences.
            </motion.p>

            {/* BUTTONS */}

            <motion.div
              initial={{ opacity: 0, y: 25 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.5 }}
              className="
                mt-7
                flex
                flex-col
                items-center
                gap-3
              "
            >
              {/* BUTTON 1 */}

              <Link
                href="/democatalog/gallerypage"
                className="w-auto"
              >
                <button
                  className="
                    px-6
                    py-2.5
                    rounded-full
                    bg-[#fed42a]
                    text-black
                    font-semibold
                    text-[13px]
                    transition-all
                    duration-300
                    hover:scale-105
                  "
                >
                  Explore Gallery
                </button>
              </Link>

              {/* BUTTON 2 */}

              <Link
                href="/contact/contactsection"
                className="w-auto"
              >
                <button
                  className="
                    px-6
                    py-2.5
                    rounded-full
                    border
                    border-white/30
                    bg-[#111111]
                    text-white
                    font-medium
                    text-[13px]
                    transition-all
                    duration-300
                    hover:border-[#fed42a]
                    hover:text-[#fed42a]
                  "
                >
                  Contact Us
                </button>
              </Link>
            </motion.div>
          </div>
        </section>

        {/* ===================================================== */}
        {/* DESKTOP HERO SECTION */}
        {/* ===================================================== */}

        <section className="hidden md:flex relative min-h-[90vh] items-center justify-center text-center overflow-hidden px-4 sm:px-6">
          {/* Background Image */}

          <Image
            src="/tms product/Product Banner1.jpg"
            alt="Products"
            fill
            priority
            className="object-fill object-center mt-4 "
          />

          {/* Overlay */}

          <div className="absolute inset-0 bg-gradient-to-r from-black/20 via-black/20 to-black/20"></div>

          {/* Content */}

          <div
            className="relative z-10 max-w-4xl mx-auto w-full"
            data-aos="fade-up"
          >
            {/* Heading */}

            <motion.h1
              initial={{ opacity: 0, y: 40 }}
              whileInView={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.7 }}
              className="
                text-5xl
                md:text-6xl
                font-bold
                leading-tight
              "
            >
              Our{" "}
              <span className="text-[#fed42a]">
                Product Line
              </span>
            </motion.h1>

            {/* Description */}

            <motion.p
              initial={{ opacity: 0, y: 30 }}
              whileInView={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.9 }}
              className="
                text-white
                mt-5
                text-lg
                leading-relaxed
                max-w-2xl
                mx-auto
              "
            >
              Carefully selected beauty and health technologies
              from Korea, designed to redefine modern wellness
              experiences.
            </motion.p>





            

            {/* Buttons */}

           <div className="mt-10 flex flex-col sm:flex-row items-center justify-center gap-5">

      {/* Watch Demo Button */}
      <Link href="/democatalog/gallerypage">
      <button
      className="group relative overflow-hidden px-8 py-4 rounded-full border border-[#fed42a]/40 bg-[#fed42a] text-black font-semibold transition-all duration-500 hover:scale-105"
    >
      {/* Overlay */}
      <span className="absolute inset-0 bg-black translate-y-full group-hover:translate-y-0 transition-transform duration-500"></span>

      {/* Text */}
      <span className="relative z-10 transition duration-500 group-hover:text-[#fed42a]">
        Explore Gallery
      </span>
    </button>
      </Link>

      {/* Download Catalog Button */}
      <Link href="/contact/contactsection">
       <button
      className="group relative overflow-hidden px-8 py-4 rounded-full border border-white/20 bg-white/5 backdrop-blur-md text-white font-medium transition-all duration-500 hover:scale-105"
    >
      {/* Overlay */}
      <span className="absolute inset-0 bg-white translate-y-full group-hover:translate-y-0 transition-transform duration-500"></span>

      {/* Text */}
      <span className="relative z-10 transition duration-500 group-hover:text-black">
        Contact Us
      </span>
    </button>
      </Link>

    </div>          </div>

          {/* Bottom Fade */}

          <div className="absolute bottom-0 left-0 w-full h-20 sm:h-32 bg-gradient-to-t from-black to-transparent"></div>
        </section>

        {/* ===================================================== */}
        {/* PRODUCTS SECTION */}
        {/* ===================================================== */}

        <section className="max-w-7xl mx-auto px-4 sm:px-6 md:px-10 py-16 sm:py-24 space-y-20 sm:space-y-28 overflow-hidden">
          {products.map((product, index) => (
            <div
              key={index}
              className="grid grid-cols-1 md:grid-cols-2 gap-10 lg:gap-14 items-center"
            >
              {/* IMAGE */}

              <motion.div
                initial={{ opacity: 0, x: index % 2 === 0 ? -60 : 60 }}
                whileInView={{ opacity: 1, x: 0 }}
                transition={{ duration: 0.7 }}
                data-aos="fade-up"
                className={`
                  relative
                  h-[280px]
                  sm:h-[380px]
                  md:h-[480px]
                  rounded-3xl
                  overflow-hidden
                  border
                  border-[#222]
                  group
                  ${index % 2 !== 0 ? "md:order-2" : ""}
                `}
              >
                <Image
                  src={product.image}
                  alt={product.name}
                  fill
                  className="object-cover group-hover:scale-105 transition duration-700"
                />

                {/* Overlay */}

                <div className="absolute inset-0 bg-gradient-to-t from-black/80 to-black/10"></div>

                {/* Floating Label */}

                <div className="absolute top-5 left-5 sm:top-6 sm:left-6">
                  <p className="text-[10px] sm:text-xs tracking-[4px] sm:tracking-[6px] text-white/70 uppercase">
                    {product.name}
                  </p>
                </div>

                {/* Bottom Text */}

                <div className="absolute bottom-6 left-5 right-5 sm:bottom-8 sm:left-6 sm:right-6">
                  <h2 className="text-2xl sm:text-4xl md:text-5xl font-bold leading-tight">
                    {product.title}
                  </h2>

                  <p className="text-[#fed42a] mt-3 text-sm md:text-base">
                    {product.subtitle}
                  </p>
                </div>
              </motion.div>

              {/* CONTENT */}

              <motion.div
                initial={{ opacity: 0, x: index % 2 === 0 ? 60 : -60 }}
                whileInView={{ opacity: 1, x: 0 }}
                transition={{ duration: 0.7 }}
                data-aos="fade-up"
                className="space-y-6"
              >
                <div>
                  <h3 className="text-2xl sm:text-3xl md:text-4xl font-semibold text-[#fed42a]">
                    {product.name} Therapy System
                  </h3>

                  <div className="w-20 h-[2px] bg-[#fed42a] mt-3"></div>
                </div>

                <p className="text-gray-300 leading-relaxed text-sm sm:text-base">
                  {product.description}
                </p>

                <p className="text-gray-500 leading-relaxed text-sm">
                  {product.extra}
                </p>

                {/* Benefits */}

                <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 pt-4">
                  {product.benefits.map((item, i) => (
                    <div
                      key={i}
                      className="
                        flex
                        items-start
                        gap-3
                        p-4
                        border
                        border-[#222]
                        rounded-xl
                        hover:border-[#fed42a]/40
                        transition
                      "
                    >
                      <div className="w-2 h-2 bg-[#fed42a] rounded-full mt-2"></div>

                      <p className="text-gray-300 text-sm">
                        {item}
                      </p>
                    </div>
                  ))}
                </div>

                {/* Button */}

                <div className="pt-4">
                  <Link href="/democatalog/democatalogpage">
                    <button
                      className="
                        group
                        relative
                        overflow-hidden
                        w-full
                        sm:w-auto
                        min-w-[220px]
                        px-8
                        py-3.5
                        rounded-full
                        border
                        border-[#fed42a]/40
                        bg-[#fed42a]/10
                        backdrop-blur-md
                        text-white
                        font-medium
                        text-sm
                        sm:text-base
                        transition-all
                        duration-500
                        hover:scale-105 max-sm:w-12
                      "
                    >
                      <span className="absolute inset-0 bg-[#fed42a] translate-y-full group-hover:translate-y-0 transition-transform duration-500"></span>

                      <span className="relative z-10  group-hover:text-black transition duration-500">
                        Learn More
                      </span>
                    </button>
                  </Link>
                </div>
              </motion.div>
            </div>
          ))}
        </section>

        {/* ===================================================== */}
        {/* PRODUCT GALLERY */}
        {/* ===================================================== */}

        <section className="py-16 sm:py-24 px-4 sm:px-6 md:px-10 bg-[#0a0a0a] overflow-hidden">
          <div className="max-w-7xl mx-auto">
            {/* Heading */}

            <div
              className="text-center mb-14 sm:mb-16"
              data-aos="fade-up"
            >
              <h2 className="text-3xl sm:text-4xl md:text-5xl font-bold">
                Product{" "}
                <span className="text-[#fed42a]">
                  Gallery
                </span>
              </h2>

              <p className="text-gray-400 mt-4 text-sm sm:text-base">
                Explore our premium beauty and healthcare technologies.
              </p>
            </div>

            {/* Gallery Grid */}

            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
              {galleryImages.map((img, index) => (
                <motion.div
                  key={index}
                  whileHover={{ scale: 1.03 }}
                  data-aos="zoom-in"
                  className="
                    relative
                    h-[240px]
                    sm:h-[260px]
                    rounded-3xl
                    overflow-hidden
                    group
                    border
                    border-[#222]
                  "
                >
                  <Image
                    src={img}
                    alt="Gallery"
                    fill
                    className="object-cover group-hover:scale-110 transition duration-700"
                  />

                  <div className="absolute inset-0 bg-black/20 group-hover:bg-black/40 transition duration-500"></div>
                </motion.div>
              ))}
            </div>
          </div>
        </section>

        {/* ===================================================== */}
        {/* CTA SECTION */}
        {/* ===================================================== */}

        <section className="py-16 sm:py-24 px-4 sm:px-6 text-center overflow-hidden">
          <div
            className="max-w-4xl mx-auto"
            data-aos="fade-up"
          >
            <h2 className="text-3xl sm:text-4xl md:text-5xl font-bold leading-tight">
              Discover Advanced Beauty & Healthcare Solutions
            </h2>

            <p className="text-gray-400 mt-5 max-w-2xl mx-auto text-sm sm:text-base leading-relaxed">
              Connect with BH Connected and explore premium Korean
              innovation designed for modern wellness experiences.
            </p>

            {/* Buttons */}

            <div className="mt-10 flex flex-col sm:flex-row items-center justify-center gap-5">
              <Link
                href="/contact/contactsection"
                className="w-full sm:w-auto"
              >
                <button
                  className="
                    w-full
                    sm:w-auto
                    min-w-[220px]
                    px-10
                    py-3.5
                    rounded-full
                    bg-[#fed42a]
                    text-black
                    font-semibold
                    text-sm
                    sm:text-base
                    hover:bg-yellow-300
                    hover:scale-105
                    transition-all
                    duration-300 max-sm:w-12
                  "
                >
                  Contact Us
                </button>
              </Link>

              <Link
                href="/products/downloadcatalogeflyer"
                className="w-full sm:w-auto"
              >
                <button
                  className="
                    w-full
                    sm:w-auto
                    min-w-[220px]
                    px-10
                    py-3.5
                    rounded-full
                    border
                    border-white/20
                    bg-white/5
                    backdrop-blur-md
                    text-white
                    text-sm
                    sm:text-base
                    hover:border-[#fed42a]
                    hover:text-[#fed42a]
                    hover:scale-105
                    transition-all
                    duration-300 max-sm:w-12
                  "
                >
                  Download Brochure
                </button>
              </Link>
            </div>
          </div>
        </section>
      </div>
    </App_layout>
  );
}