"use client";

import Image from "next/image";
import App_layout from "@/layout/app_layout";
import { motion } from "framer-motion";

const products = [
  {
    name: "TMS",
    image: "/home/altms.jpg",
    title: "Transcranial Magnetic Stimulation",
    subtitle: "FDA-Cleared TMS Therapy",
    description:
      "TMS therapy is a non-invasive treatment in which a strong electromagnetic field generated by a coil penetrates the skull and stimulates nerve cells. The electromagnetic field reaching the cerebral cortex induces electric currents within neurons, activating or inhibiting brain activity.",
    extra:
      "To date, the U.S. FDA has cleared TMS for the treatment of major depressive disorder, anxiety, obsessive-compulsive disorder, and smoking addiction. It is also being studied as a solution for various drug-resistant and refractory conditions.",
    benefits: [
      "Non-invasive treatment solution",
      "Clinically proven effectiveness",
      "Safe and patient-friendly",
      "Enhances neurological outcomes",
    ],
  },

  {
    name: "PMS",
    image: "/home/salus-1.jpg",
    title: "Pain Management Solution",
    subtitle: "Comprehensive Pain Treatment Solution by REMED",
    description:
      "Pro Performance, Pro Features, Pro Results. Premium Electromagnetic Stimulator designed for more precise pain therapy via two applicators for whole-body and localized stimulation.",
    extra:
      "User-centered manual modes, flexible angles with 3D Angle Arm, and cooling system for continuous use.",
    benefits: [
      "User-centered manual modes",
      "Flexible angles with 3D Angle Arm",
      "Cooling system for continuous use",
      "Precise whole-body stimulation",
    ],
  },
];

export default function ProductsPage() {
  return (
    <App_layout>
      <div className="bg-black text-white overflow-hidden">

        {/* 🔹 PAGE HEADER */}
        <section className="relative py-32 px-6 text-center overflow-hidden">

          {/* Glow */}
          <div className="absolute top-0 left-1/2 -translate-x-1/2 w-[500px] h-[500px] bg-[#fed42a]/10 blur-[150px] rounded-full"></div>

          <div className="relative z-10 max-w-3xl mx-auto">
            <motion.h1
              initial={{ opacity: 0, y: 40 }}
              whileInView={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.7 }}
              className="text-4xl md:text-5xl font-bold"
            >
              Our <span className="text-[#fed42a]">Product Line</span>
            </motion.h1>

            <motion.p
              initial={{ opacity: 0, y: 30 }}
              whileInView={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.9 }}
              className="text-gray-400 mt-4"
            >
              Carefully selected beauty and health technologies from Korea.
            </motion.p>
          </div>
        </section>

        {/* 🔹 PRODUCTS */}
        <section className="max-w-7xl mx-auto px-6 md:px-10 pb-24 space-y-28">

          {products.map((product, index) => (
            <div
              key={index}
              className="grid md:grid-cols-2 gap-14 items-center"
            >

              {/* IMAGE */}
              <motion.div
                initial={{ opacity: 0, x: index % 2 === 0 ? -60 : 60 }}
                whileInView={{ opacity: 1, x: 0 }}
                transition={{ duration: 0.7 }}
                className={`relative h-[300px] sm:h-[400px] md:h-[500px] rounded-3xl overflow-hidden border border-[#222] group ${
                  index % 2 !== 0 ? "md:order-2" : ""
                }`}
              >
                <Image
                  src={product.image}
                  alt={product.name}
                  fill
                  className="object-cover group-hover:scale-105 transition duration-700"
                />

                {/* Overlay */}
                <div className="absolute inset-0 bg-gradient-to-t from-black/80 to-black/10"></div>

                {/* Floating Label */}
                <div className="absolute top-6 left-6">
                  <p className="text-xs tracking-[6px] text-white/70 uppercase">
                    {product.name}
                  </p>
                </div>

                {/* Bottom Text */}
                <div className="absolute bottom-8 left-6 right-6">
                  <h2 className="text-3xl md:text-5xl font-bold leading-tight">
                    {product.title}
                  </h2>

                  <p className="text-[#fed42a] mt-3 text-sm md:text-base">
                    {product.subtitle}
                  </p>
                </div>
              </motion.div>

              {/* CONTENT */}
              <motion.div
                initial={{ opacity: 0, x: index % 2 === 0 ? 60 : -60 }}
                whileInView={{ opacity: 1, x: 0 }}
                transition={{ duration: 0.7 }}
                className="space-y-6"
              >

                <div>
                  <h3 className="text-2xl md:text-3xl font-semibold text-[#fed42a]">
                    {product.name} Therapy System
                  </h3>

                  <div className="w-20 h-[2px] bg-[#fed42a] mt-3"></div>
                </div>

                <p className="text-gray-300 leading-relaxed text-sm md:text-base">
                  {product.description}
                </p>

                <p className="text-gray-500 leading-relaxed text-sm">
                  {product.extra}
                </p>

                {/* BENEFITS */}
                <div className="grid sm:grid-cols-2 gap-4 pt-4">

                  {product.benefits.map((item, i) => (
                    <div
                      key={i}
                      className="flex items-start gap-3 p-4 border border-[#222] rounded-xl hover:border-[#fed42a]/40 transition"
                    >
                      <div className="w-2 h-2 bg-[#fed42a] rounded-full mt-2"></div>

                      <p className="text-gray-300 text-sm">
                        {item}
                      </p>
                    </div>
                  ))}

                </div>

              </motion.div>

            </div>
          ))}

        </section>

      </div>
    </App_layout>
  );
}